"""add payroll tables

Revision ID: 32299336a743
Revises: 
Create Date: 2026-06-16 11:08:40.302308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32299336a743'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_cycle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('pay_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PROCESSING', 'APPROVED', 'PAID', 'CANCELLED', name='payrollcyclestatus'), nullable=False),
    sa.Column('totals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_cycle_company_id'), 'payroll_cycle', ['company_id'], unique=False)
    op.create_index(op.f('ix_payroll_cycle_id'), 'payroll_cycle', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_slug'), 'user', ['slug'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('payslip',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('gross_earnings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_pay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('lop_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('paid_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('earnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deductions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', name='payslipstatus'), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['payroll_cycle.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'employee_id', name='uq_payslip_cycle_employee')
    )
    op.create_index(op.f('ix_payslip_company_id'), 'payslip', ['company_id'], unique=False)
    op.create_index(op.f('ix_payslip_cycle_id'), 'payslip', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_payslip_employee_id'), 'payslip', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payslip_id'), 'payslip', ['id'], unique=False)
    op.create_table('salary_structure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('ctc', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('pay_frequency', sa.String(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default_deductions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_active_salary_structure', 'salary_structure', ['employee_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_index(op.f('ix_salary_structure_company_id'), 'salary_structure', ['company_id'], unique=False)
    op.create_index(op.f('ix_salary_structure_employee_id'), 'salary_structure', ['employee_id'], unique=False)
    op.create_index(op.f('ix_salary_structure_id'), 'salary_structure', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salary_structure_id'), table_name='salary_structure')
    op.drop_index(op.f('ix_salary_structure_employee_id'), table_name='salary_structure')
    op.drop_index(op.f('ix_salary_structure_company_id'), table_name='salary_structure')
    op.drop_index('idx_active_salary_structure', table_name='salary_structure', postgresql_where=sa.text('is_active = true'))
    op.drop_table('salary_structure')
    op.drop_index(op.f('ix_payslip_id'), table_name='payslip')
    op.drop_index(op.f('ix_payslip_employee_id'), table_name='payslip')
    op.drop_index(op.f('ix_payslip_cycle_id'), table_name='payslip')
    op.drop_index(op.f('ix_payslip_company_id'), table_name='payslip')
    op.drop_table('payslip')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_slug'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_payroll_cycle_id'), table_name='payroll_cycle')
    op.drop_index(op.f('ix_payroll_cycle_company_id'), table_name='payroll_cycle')
    op.drop_table('payroll_cycle')
    # ### end Alembic commands ###
