import uuid
from datetime import datetime

from typing import Any

from sqlalchemy import LargeBinary, String, func, text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models import Base


class TimestampMixin:
    """Audit columns shared by every table (spec §2)."""

    created_at: Mapped[datetime] = mapped_column(server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        server_default=func.now(), onupdate=func.now()
    )
    deleted_at: Mapped[datetime | None] = mapped_column(default=None, nullable=True)


class Company(Base, TimestampMixin):
    """Tenant. Every business row carries a company_id FK to this table."""

    __tablename__ = "companies"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("uuid_generate_v4()"),
    )
    name: Mapped[str] = mapped_column(String(160))
    currency: Mapped[str] = mapped_column(String(8), default="INR")

    # ----- Organisation profile (Settings → Organisation Profile) -----
    # All optional; populated/edited from the Settings screen. Mirrors Zoho
    # Payroll's Organisation Profile (basic details + address + tax identifiers).
    legal_name: Mapped[str | None] = mapped_column(String(200), nullable=True)
    industry: Mapped[str | None] = mapped_column(String(120), nullable=True)
    contact_email: Mapped[str | None] = mapped_column(String(255), nullable=True)
    contact_phone: Mapped[str | None] = mapped_column(String(32), nullable=True)
    address_line1: Mapped[str | None] = mapped_column(String(200), nullable=True)
    address_line2: Mapped[str | None] = mapped_column(String(200), nullable=True)
    city: Mapped[str | None] = mapped_column(String(120), nullable=True)
    state: Mapped[str | None] = mapped_column(String(120), nullable=True)
    pincode: Mapped[str | None] = mapped_column(String(16), nullable=True)
    country: Mapped[str] = mapped_column(String(80), default="India", server_default="India")
    # Org-level statutory tax identifiers (Zoho "Tax Information").
    pan: Mapped[str | None] = mapped_column(String(10), nullable=True)
    tan: Mapped[str | None] = mapped_column(String(10), nullable=True)

    # ----- Payslip template (Settings → Payslip) -----
    # Per-company payslip branding + section toggles, applied to both the PDF
    # and the web/print view. Stored as a JSON blob (see schema.settings
    # PayslipSettings for the shape + defaults); NULL/missing keys fall back to
    # built-in defaults at render time, so existing companies keep working.
    payslip_settings: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)

    # ----- Statutory configuration (Settings → Statutory Compliance) -----
    # Per-company overrides for the flat statutory rates/thresholds (PF/ESI/TDS
    # scalars). See schema.settings StatutoryConfig for the shape + defaults;
    # NULL/missing keys fall back to the code constants at compute time.
    statutory_settings: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)

    # ----- Uploaded payslip document template (Settings → Payslip) -----
    # An optional .docx the admin uploads with Jinja tokens (docxtpl). When set
    # and enabled (payslip_settings.use_doc_template), payslips are generated by
    # filling this template instead of the built-in layout.
    payslip_doc_template: Mapped[bytes | None] = mapped_column(LargeBinary, nullable=True)
    payslip_doc_filename: Mapped[str | None] = mapped_column(String(255), nullable=True)
    # When the template was produced by the "smart mapping" wizard, we keep the
    # admin's ORIGINAL upload (token-free) here so they can re-run the wizard,
    # plus the confirmed {slot_index: token} mapping for display. The token-filled
    # result lives in payslip_doc_template above (what generation actually uses).
    payslip_doc_original: Mapped[bytes | None] = mapped_column(LargeBinary, nullable=True)
    payslip_doc_mapping: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
